### ISSUE TITLE
problem with 1 anchor + 2 tags or more

### ISSUE THREAD

**Issue by sabrinalek** [jremington/UWB-Indoor-Localization_Arduino#10]
hello, 
i'm struggling with implementation of multiple Tags in DW1000 makerfabs,
1 anchor can't track more than 1 tags at the same time. 
and me i want to implemente 10 tags + 4 anchor. have you any sollution for this probleme please?
is it a bug in the library?

**Comment by jremington** [comment]
The code that I posted is intended for 1 tag and is limited to four anchors.

It might be possible to have 2 or more tags with four anchors. I have not tried thought much about, or tried that.

**Comment by sabrinalek** [comment]
Hello,
when I try to add more tags, the measurements are not reliable and I loose connection to the anchors. Is there an example of multi-tag implementation? Thank you

**Comment by jremington** [comment]
I don't know of a working example.
