### ISSUE TITLE
Compile error, what reason?

### ISSUE THREAD

**Issue by arthur9188** [jremington/UWB-Indoor-Localization_Arduino#13]
C:\Users\Administrator\AppData\Local\Temp\.arduinoIDE-unsaved2023423-5404-1kxwiif.s4g\ESP32_anchor_autocalibrate\ESP32_anchor_autocalibrate.ino: In function 'void setup()':
C:\Users\Administrator\AppData\Local\Temp\.arduinoIDE-unsaved2023423-5404-1kxwiif.s4g\ESP32_anchor_autocalibrate\ESP32_anchor_autocalibrate.ino:44:12: error: no matching function for call to 'SPIClass::begin(int, int, int)'
   44 |   SPI.begin(SPI_SCK, SPI_MISO, SPI_MOSI);
      |   ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:\Users\Administrator\AppData\Local\Temp\.arduinoIDE-unsaved2023423-5404-1kxwiif.s4g\ESP32_anchor_autocalibrate\ESP32_anchor_autocalibrate.ino:15:
C:\Users\Administrator\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.5.0\libraries\SPI\src/SPI.h:151:18: note: candidate: 'virtual void SPIClass::begin(uint8_t)'
  151 |     virtual void begin(uint8_t _pin = CS_PIN_CONTROLLED_BY_USER);
      |                  ^~~~~
C:\Users\Administrator\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.5.0\libraries\SPI\src/SPI.h:151:18: note:   candidate expects 1 argument, 3 provided

exit status 1

Compilation error: no matching function for call to 'SPIClass::begin(int, int, int)'

**Comment by jremington** [comment]
The posted code was written for ESP32 and will need to be modified for STM32 processors.
