### ISSUE TITLE
Issue using more than 4 Anchors

### ISSUE THREAD

**Issue by jhoydich** [jremington/UWB-Indoor-Localization_Arduino#14]
I tried the 3D localization problem utilizing 5 anchors to over constrain the LLS solution. Oddly enough the tag functioned properly when interfacing with 4 anchors, but once the 5th anchor was added, the tag basically halted the ranging protocol only returning ranges sporadically. I do not believe the issue is interfacing with 5 anchors. Currently I think the issue is with how `_timerDelay` variable is calculated for subsequent anchors. For a 5th anchor, the value is 171 ms which is close to the 200 ms  value of `_resetPeriod`. I'll experiment some more and create a merge request if successful.

**Comment by jremington** [comment]
The "4A" code is currently configured for **4 anchors**, maximum. It would not be difficult to change the array dimensions to accommodate more, although 7 tags total is the maximum allowed for the addressing scheme as it now stands. 

I did not have 5 anchors to test, so did not get around to implementing the required changes.

**Comment by jhoydich** [comment]
This issue was not using that example. My tag implementation is pretty much bare bones and my anchors are publishing ranges to a computer that handles the calculation.

I think the issue is in the underlying library.

**Comment by jremington** [comment]
I can't possibly comment on your example, not having seen the code.  The localization code I wrote simply requires a set of distances, and does not use the DW1000 library.

**Comment by jhoydich** [comment]
Sorry if I was not clear, the issue is not with localization. If a tag connects to over 4 anchors then the ranging loop basically becomes extremely sporadic, meaning the tag will send/reply to a ranging message every 10 to 20 seconds (if at all).

I intend to figure out the solution as I have the necessary hardware. I just wanted to post the issue here in case anyone else runs into the same issue. It seems like this was what #7 was experiencing as well.

**Comment by jremington** [comment]
Fair enough. Are you using the original Thomas Trojer DW1000 library, or the modified version I posted here? 

The DW1000 library DOES have a limit on the number of devices that can be active, which I increased from 4 to 7. See DW1000Ranging.h

**Comment by jhoydich** [comment]
I've been using yours, but I'm sure this issue exists in his library as well. I just think there is some funky stuff going on with the various delay values in the DW1000Ranging file.

Yeah I did notice that constant. I'm curious if there was a reason he chose 4, but I doubt I would get a reply if asked.
