### ISSUE TITLE
TWR Implementation Speed Program

### ISSUE THREAD

**Issue by anthony211212** [jremington/UWB-Indoor-Localization_Arduino#18]
Hello. How can we speed up the program? What changes should we make in this regard? I've looked into the code, but I'm not sure if removing delay commands would provide a complete solution. I think increasing the speed might also improve accuracy.

**Comment by anthony211212** [comment]
What you said is correct, however, reading incoming data quickly will increase accuracy. Also, I would like to ask you this: What does the 'fast' and 'short' data situation mean in modes labeled as LONGDATA_RANGE_LOWPOWER, SHORTDATA_FAST_LOWPOWER? Wouldn't the difference between these two increase accuracy? For example, wouldn't a higher transmission rate and pulse frequency increase accuracy?

**Comment by jremington** [comment]
Try it and see.

**Comment by Nate5461** [comment]
Hi, I am trying to experiment with the different modes offered but cannot get the anchor and tag to connect when not using the default mode that it came set as. I have changed the mode on both anchor and tag but they seem unable to see each other. They should be synchronized as all I've done is changed them to the same mode from the same library. Do you have any idea what I need to change or what I'm missing?

**Comment by jremington** [comment]
Please post examples showing how you have changed the code for both anchor and tag. 

Make sure that you are linking with the modified DW1000 library and identify which one (low or high power).

**Comment by Nate5461** [comment]
Here is the anchor_setup and tag_setup (I'm just trying to get them to find each other at different mode). I have both high and standard library that came with this repo included, shown on the left.
![Screenshot (66)](https://github.com/jremington/UWB-Indoor-Localization_Arduino/assets/99362931/a3274860-c22e-4826-91b9-4139cdb94364)
![Screenshot (67)](https://github.com/jremington/UWB-Indoor-Localization_Arduino/assets/99362931/f4174a11-2216-49f0-a38c-4c1f1d1fa115)
![Screenshot (68)](https://github.com/jremington/UWB-Indoor-Localization_Arduino/assets/99362931/4348f2ee-ff6d-4da7-a93f-57df4973894a)

**Comment by jremington** [comment]
Please post code using code tags, not as screen shots.

You MUST use the version of Thomas Trojer's library as modified and posted in this repository.

**Comment by Nate5461** [comment]
`//anchor  setup


// be sure to edit anchor_addr and select the previously calibrated anchor delay
// my naming convention is anchors 1, 2, 3, ... have the lowest order byte of the MAC address set to 81, 82, 83, ...
#include <Arduino.h>
#include <SPI.h>
#include "DW1000Ranging.h"
#include "DW1000.h"

// leftmost two bytes below will become the "short address"
char anchor_addr[] = "81:00:5B:D5:A9:9A:E2:9C"; //#1
//char anchor_addr[] = "82:00:5B:D5:A9:9A:E2:9C"; //#2
//char anchor_addr[] = "83:00:5B:D5:A9:9A:E2:9C"; //#3
//char anchor_addr[] = "84:00:5B:D5:A9:9A:E2:9C"; //#4


//calibrated Antenna Delay setting for this anchor
uint16_t Adelay = 16789;

// previously determined calibration results for antenna delay
// #1 16630
// #2 16610
// #3 16607
// #4 16580

// calibration distance
float dist_m = (285 - 1.75) * 0.0254; //meters

#define SPI_SCK 18
#define SPI_MISO 19
#define SPI_MOSI 23
#define DW_CS 4

// connection pins
const uint8_t PIN_RST = 27; // reset pin
const uint8_t PIN_IRQ = 34; // irq pin
const uint8_t PIN_SS = 4;   // spi select pin

void newRange()
{
  //    Serial.print("from: ");
  Serial.print(DW1000Ranging.getDistantDevice()->getShortAddress(), HEX);
  Serial.print(", ");

#define NUMBER_OF_DISTANCES 1
  float dist = 0.0;
  for (int i = 0; i < NUMBER_OF_DISTANCES; i++) {
    dist += DW1000Ranging.getDistantDevice()->getRange();
  }
  dist = dist/NUMBER_OF_DISTANCES;
  Serial.println(dist);
}

void newDevice(DW1000Device *device)
{
  Serial.print("Device added: ");
  Serial.println(device->getShortAddress(), HEX);
}

void inactiveDevice(DW1000Device *device)
{
  Serial.print("Delete inactive device: ");
  Serial.println(device->getShortAddress(), HEX);
}


void setup()
{
  Serial.begin(115200);
  delay(1000); //wait for serial monitor to connect
  Serial.println("Anchor config and start");
  Serial.print("Antenna delay ");
  Serial.println(Adelay);
  Serial.print("Calibration distance ");
  Serial.println(dist_m);

  //init the configuration
  SPI.begin(SPI_SCK, SPI_MISO, SPI_MOSI);
  DW1000Ranging.initCommunication(PIN_RST, PIN_SS, PIN_IRQ); //Reset, CS, IRQ pin

  // set antenna delay for anchors only. Tag is default (16384)
  DW1000.setAntennaDelay(Adelay);

  DW1000Ranging.attachNewRange(newRange);
  DW1000Ranging.attachNewDevice(newDevice);
  DW1000Ranging.attachInactiveDevice(inactiveDevice);

  //start the module as an anchor, do not assign random short address
  DW1000Ranging.startAsAnchor(anchor_addr, DW1000.MODE_LONGDATA_RANGE_LOWPOWER, false);
  // DW1000Ranging.startAsAnchor(ANCHOR_ADD, DW1000.MODE_SHORTDATA_FAST_LOWPOWER);
  // DW1000Ranging.startAsAnchor(ANCHOR_ADD, DW1000.MODE_LONGDATA_FAST_LOWPOWER);
  // DW1000Ranging.startAsAnchor(ANCHOR_ADD, DW1000.MODE_SHORTDATA_FAST_ACCURACY);
  // DW1000Ranging.startAsAnchor(ANCHOR_ADD, DW1000.MODE_LONGDATA_FAST_ACCURACY);
  // DW1000Ranging.startAsAnchor(ANCHOR_ADD, DW1000.MODE_LONGDATA_RANGE_ACCURACY);
}

void loop()
{
  DW1000Ranging.loop();
}

`
Tag setup:
`// currently tag is module #5
// The purpose of this code is to set the tag address and antenna delay to default.
// this tag will be used for calibrating the anchors.

#include <Arduino.h>
#include <SPI.h>
#include "DW1000Ranging.h"
#include "DW1000.h"

#define SPI_SCK 18
#define SPI_MISO 19
#define SPI_MOSI 23
#define DW_CS 4

// connection pins
const uint8_t PIN_RST = 27; // reset pin
const uint8_t PIN_IRQ = 34; // irq pin
const uint8_t PIN_SS = 4;   // spi select pin

// TAG antenna delay defaults to 16384
// leftmost two bytes below will become the "short address"
char tag_addr[] = "7D:00:22:EA:82:60:3B:9C";

void newRange()
{
  Serial.print(DW1000Ranging.getDistantDevice()->getShortAddress(), HEX);
  Serial.print(",");
  Serial.println(DW1000Ranging.getDistantDevice()->getRange());
}

void newDevice(DW1000Device *device)
{
  Serial.print("Device added: ");
  Serial.println(device->getShortAddress(), HEX);
}

void inactiveDevice(DW1000Device *device)
{
  Serial.print("delete inactive device: ");
  Serial.println(device->getShortAddress(), HEX);
}

void setup()
{
  Serial.begin(115200);
  delay(1000);

  //init the configuration
  SPI.begin(SPI_SCK, SPI_MISO, SPI_MOSI);
  DW1000Ranging.initCommunication(PIN_RST, PIN_SS, PIN_IRQ); //Reset, CS, IRQ pin

  DW1000Ranging.attachNewRange(newRange);
  DW1000Ranging.attachNewDevice(newDevice);
  DW1000Ranging.attachInactiveDevice(inactiveDevice);

// start as tag, do not assign random short address

  DW1000Ranging.startAsTag(tag_addr, DW1000.MODE_LONGDATA_RANGE_LOWPOWER, false);
}

void loop()
{
  DW1000Ranging.loop();
}

`
I am using the modified library, I pulled from the repository 2 days ago and dragged that exact library in

**Comment by Nate5461** [comment]
I have deleted the highpower library and now it seems to work with just the standard library

**Comment by anthony211212** [comment]
How many anchors and tags do you have in your setup?
