### ISSUE TITLE
read the wrong address

### ISSUE THREAD

**Issue by hongthiet1994** [jremington/UWB-Indoor-Localization_Arduino#2]
![image](https://user-images.githubusercontent.com/29925688/180720415-0290951d-bd5b-4439-aa5e-dd0a323560e9.png)

I had write short add address to DWM1000, but when i read address from DWM1000 always get 130

i have 6 board DWM1000, but have only 2 boards have this error.

Please help me !

**Comment by jremington** [comment]
That sounds like a problem with the chip.
 
The "short address" is just the lowest two bytes of the MAC address that you assign. (0x7D in the two lines below:
```
// leftmost two bytes below will become the "short address"
char tag_addr[] = "7D:00:22:EA:82:60:3B:9C";
```

Post the code showing the address(es) you are trying to assign.
