### ISSUE TITLE
Error read temperature and voltage of DWM1000

### ISSUE THREAD

**Issue by hongthiet1994** [jremington/UWB-Indoor-Localization_Arduino#4]
I used DW1000.getTempAndVbat(temp,volt) to read value temperature and voltage but value not true

temp : -132.039993, volt: 2.513873

->> i think value voltage may be true, but value temperature not good
Is anyone else having the same error as me?

**Comment by jremington** [comment]
The code for the function getTempAndVbat() is from the original DW1000 library by Thomas Trojer.

If you look carefully at that code, it relies on baseline values stored in the OTP memory of each DW1000 module during "production run tests". 

When using the DW1000 modules used in the  MakerFabs ESP32-DW1000 boards, be aware that those are not from DecaWave, and may not have the required baseline data stored in OTP memory. That is a question to ask of MakerFabs.

**Comment by hongthiet1994** [comment]
thank you so much

**Comment by j-shirazi** [comment]
I am using the original Decawave DWM1000 with an ESP32 and have the same problem! How can I fix this? can calibrate the temp sensor myself?
