### ISSUE TITLE
5 Anchors 

### ISSUE THREAD

**Issue by dmasloub** [jremington/UWB-Indoor-Localization_Arduino#6]
When I try to extend the 3D Indoor Localization to a System with 5 Anchors, the Tag receives distance only every 20 or so seconds. 
I also tried to connect the tag with 5 Anchors without any Math, but it still doesn't work properly. Every time I remove an Anchor distances come in fine, and as soon as I add the fifth, the error occurs again. 

I used the following code to test the connecting without any further math: 
`#include <SPI.h>
#include "DW1000Ranging.h"
#include "DW1000.h"

#define SPI_SCK 18
#define SPI_MISO 19
#define SPI_MOSI 23
#define DW_CS 4

// connection pins
const uint8_t PIN_RST = 27; // reset pin
const uint8_t PIN_IRQ = 34; // irq pin
const uint8_t PIN_SS = 4;   // spi select pin

// TAG antenna delay defaults to 16384
// leftmost two bytes below will become the "short address"
char tag_addr[] = "7D:00:22:EA:82:60:3B:9C";

// global variables, input and output

void setup()
{
  Serial.begin(115200);
  delay(1000);

  //initialize configuration
  SPI.begin(SPI_SCK, SPI_MISO, SPI_MOSI);
  DW1000Ranging.initCommunication(PIN_RST, PIN_SS, PIN_IRQ); //Reset, CS, IRQ pin

  DW1000Ranging.attachNewRange(newRange);
  DW1000Ranging.attachNewDevice(newDevice);
  DW1000Ranging.attachInactiveDevice(inactiveDevice);

  // start as tag, do not assign random short address

  DW1000Ranging.startAsTag(tag_addr, DW1000.MODE_SHORTDATA_FAST_LOWPOWER, false);
}

void loop()
{
  DW1000Ranging.loop();
}

// collect distance data from anchors

void newRange()
{
    int address = DW1000Ranging.getDistantDevice()-> getShortAddress(); 
    Serial.println(address, HEX); 
}  //end newRange

void newDevice(DW1000Device *device)
{
  Serial.print("Device added: ");
  Serial.println(device->getShortAddress(), HEX);
}

void inactiveDevice(DW1000Device *device)
{
  Serial.print("delete inactive device: ");
  Serial.println(device->getShortAddress(), HEX);
}`

I only output the shortaddress itself, since the distance doesn't really matter here, same thing happens when I output the distance. 

Any Idea what the issue could be and how to solve it? All help is greatly appreciated!!!

**Comment by dmasloub** [comment]
I also tried different modes but it doesn't work properly with any of them.

**Comment by jremington** [comment]
The 3D localization code is currently configured for at most 4 anchors, and needs a few minor modifications for 5. I'm surprised that it works at all with 5.

I've been working on generalizing the code, so that it can work with a variable number of anchors (allowing for reception dropouts), but that is not yet fully tested.

**Comment by dmasloub** [comment]
`// currently tag is module labeled #5
// This code calculates the (X,Y,Z) position in meters of a UWB tag, based on the known locations
// of four UWB anchors, labeled 1 to 4
// S. James Remington 1/2022

// This code does not average position measurements!

#include <SPI.h>
#include "DW1000Ranging.h"
#include "DW1000.h"
#include "util/m33v3.h"   //matrix and vector macro library, all loops unrolled

#define DEBUG_TRILAT   //debug output in trilateration code
#define DEBUG_DISTANCES   //print collected anchor distances for algorithm
#define DEBUG_ANCHOR_ID  // print anchor IDs and raw distances

#define SPI_SCK 18
#define SPI_MISO 19
#define SPI_MOSI 23
#define DW_CS 4

// connection pins
const uint8_t PIN_RST = 27; // reset pin
const uint8_t PIN_IRQ = 34; // irq pin
const uint8_t PIN_SS = 4;   // spi select pin

// TAG antenna delay defaults to 16384

// leftmost two bytes below will become the "short address"
char tag_addr[] = "7D:00:22:EA:82:60:3B:9C";
float current_tag_position[3] = {0}; //tag current position (meters with respect to origin anchor)
float current_distance_rmse = 0.0;  //error in distance calculations. Crude measure of coordinate error (needs to be characterized)

// variables for position determination
#define N_ANCHORS 5   //THIS VERSION WORKS ONLY WITH 4 ANCHORS. May be generalized to 5 or more.
#define N_ANCHORS_HEX 0x05
#define ANCHOR_DISTANCE_EXPIRED 10000   //measurements older than this are ignore (milliseconds)

float anchor_matrix[N_ANCHORS][3] = { //list of anchor coordinates
  {0.0, 0.0, 0.0},
  {1.6, 0.6, 0.0},
  {0.0, 0.6, 0.0},
  {0.0, 0.0, -0.76},
  {1.55, 0.0, -0.76}
};

uint32_t last_anchor_update[N_ANCHORS] = {0}; //millis() value last time anchor was seen
float last_anchor_distance[N_ANCHORS] = {0.0}; //most recent distance reports

void setup()
{
  Serial.begin(115200);
  delay(1000);

  //initialize configuration
  SPI.begin(SPI_SCK, SPI_MISO, SPI_MOSI);
  DW1000Ranging.initCommunication(PIN_RST, PIN_SS, PIN_IRQ); //Reset, CS, IRQ pin

  DW1000Ranging.attachNewRange(newRange);
  DW1000Ranging.attachNewDevice(newDevice);
  DW1000Ranging.attachInactiveDevice(inactiveDevice);

  // start as tag, do not assign random short address

  DW1000Ranging.startAsTag(tag_addr, DW1000.MODE_LONGDATA_RANGE_LOWPOWER, false);
}

void loop()
{
  DW1000Ranging.loop();
}

// collect distance data from anchors, presently configured for 4 anchors
// solve for position if all four beacons are current

void newRange()
{
  int i;

  //index of this anchor, expecting values 1 to 5
  int index = DW1000Ranging.getDistantDevice()->getShortAddress() & N_ANCHORS_HEX; //expect devices 1 to 7
  Serial.println(index);
  if (index > 0) {
    last_anchor_update[index - 1] = millis();  //(-1) => array index
    float range = DW1000Ranging.getDistantDevice()->getRange();
    last_anchor_distance[index-1] = range;
    #ifdef DEBUG_ANCHOR_ID
      Serial.print(index); //anchor ID, raw range
      Serial.print(" ");
      Serial.println(range);
    #endif
    if (range < 0.0 || range > 30.0)     last_anchor_update[index - 1] = 0;  //sanity check, ignore this measurement
  }
  else {
      Serial.println("index out of range" + index);
  }


  //check for four measurements within the last interval
  int detected = 0;  //count anchors recently seen

  for (i = 0; i < N_ANCHORS; i++) {

    if (millis() - last_anchor_update[i] > ANCHOR_DISTANCE_EXPIRED) last_anchor_update[i] = 0; //not from this one
    if (last_anchor_update[i] > 0) detected++;
  }
  if ( (detected == N_ANCHORS)) { //four recent measurements

#ifdef DEBUG_DISTANCES
    // print distance and age of measurement
    uint32_t current_time = millis();
    for (i = 0; i < N_ANCHORS; i++) {
      Serial.print(last_anchor_distance[i]);
      Serial.print("\t");
      Serial.println(current_time - last_anchor_update[i]); //age in millis
    }
#endif

    //trilat3D_5A();
    test();
    Serial.print("P= ");  //result
    Serial.print(current_tag_position[0]);
    Serial.write(',');
    Serial.print(current_tag_position[1]);
    Serial.write(',');
    Serial.print(current_tag_position[2]);
    Serial.write(',');
    Serial.println(current_distance_rmse);
  }
}  //end newRange

void newDevice(DW1000Device *device)
{
  Serial.print("Device added: ");
  Serial.println(device->getShortAddress(), HEX);
}

void inactiveDevice(DW1000Device *device)
{
  Serial.print("delete inactive device: ");
  Serial.println(device->getShortAddress(), HEX);
}

int test(void){
  for (int i = 0; i < 3; i++) current_tag_position[i] = 1;
}

int trilat3D_5A(void) {

  // for method see technical paper at
  // https://www.th-luebeck.de/fileadmin/media_cosa/Dateien/Veroeffentlichungen/Sammlung/TR-2-2015-least-sqaures-with-ToA.pdf
  // S. J. Remington 1/2022
  //
  // A nice feature of this method is that the normal matrix depends only on the anchor arrangement
  // and needs to be inverted only once. Hence, the position calculation should be robust.
  //
  static bool first = true;  //first time through, some preliminary work
  float b[3], d[N_ANCHORS]; //distances from anchors

  static float Ainv[3][3], k[N_ANCHORS]; //these are calculated only once

  int i;
  // copy distances to local storage
  for (i = 0; i < N_ANCHORS; i++) d[i] = last_anchor_distance[i];

#ifdef DEBUG_TRILAT
  char line[60];
  snprintf(line, sizeof line, "d: %6.2f %6.2f %6.2f d= %6.2f", d[0], d[1], d[2], d[3]);
  Serial.println(line);
#endif

  if (first) {  //intermediate fixed vectors
    first = false;

    float x[N_ANCHORS], y[N_ANCHORS], z[N_ANCHORS]; //intermediate vectors
    float A[3][3];  //the A matrix for system of equations to solve

    for (i = 0; i < N_ANCHORS; i++) {
      x[i] = anchor_matrix[i][0];
      y[i] = anchor_matrix[i][1];
      z[i] = anchor_matrix[i][2];
      k[i] = x[i] * x[i] + y[i] * y[i] + z[i] * z[i];
    }

    // set up the A matrix
    for (i = 1; i < N_ANCHORS; i++) {
      A[i - 1][0] = x[i] - x[0];
      A[i - 1][1] = y[i] - y[0];
      A[i - 1][2] = z[i] - z[0];
#ifdef DEBUG_TRILAT
      snprintf(line, sizeof line, "A %6.2f %6.2f %6.2f", A[i - 1][0], A[i - 1][1], A[i - 1][2]);
      Serial.println(line);
#endif
    }

    float det;
    DETERMINANT_3X3 (det, A);

#ifdef DEBUG_TRILAT
    //    check solution stability (small or zero)
    Serial.print("Determinant of A matrix");
    Serial.println(det);
#endif
    if (fabs(det) < 1.0e-4) {  //TODO : define as parameter
      Serial.println("***Singular matrix, check anchor coordinates***");
      while (1) delay(1); //hang
    }

    det = 1.0 / det;
    SCALE_ADJOINT_3X3 (Ainv, det, A);  //Ainv is static

  } //end if (first)

  // set up least squares equation
  for (i = 1; i < 4; i++) {
    b[i - 1] = d[0] * d[0] - d[i] * d[i] + k[i] - k[0];
  }

  // solve:  2 A x posn = b

  float posn2[3];
  MAT_DOT_VEC_3X3(posn2, Ainv, b);
  // copy to global current_tag_position[]
  for (i = 0; i < 3; i++) current_tag_position[i] = posn2[i] * 0.5; //remove factor of 2

  //rms error in measured versus calculated distances
  float x[3] = {0}, rmse = 0.0, dc = 0.0;
  for (i = 0; i < N_ANCHORS; i++) {
    x[0] = anchor_matrix[i][0] - current_tag_position[0];
    x[1] = anchor_matrix[i][1] - current_tag_position[1];
    x[2] = anchor_matrix[i][2] - current_tag_position[2];
    dc = sqrt(x[0] * x[0] + x[1] * x[1] + x[2] * x[2]);
    rmse += (d[i] - dc) * (d[i] - dc);
  }
  current_distance_rmse = sqrt(rmse / ((float)N_ANCHORS)); //copy to global

  return 1;
}  //end trilat3D_5A`

**Comment by dmasloub** [comment]
```
// currently tag is module labeled #5
// This code calculates the (X,Y,Z) position in meters of a UWB tag, based on the known locations
// of four UWB anchors, labeled 1 to 4
// S. James Remington 1/2022

// This code does not average position measurements!

#include <SPI.h>
#include "DW1000Ranging.h"
#include "DW1000.h"
#include "util/m33v3.h"   //matrix and vector macro library, all loops unrolled

#define DEBUG_TRILAT   //debug output in trilateration code
#define DEBUG_DISTANCES   //print collected anchor distances for algorithm
#define DEBUG_ANCHOR_ID  // print anchor IDs and raw distances

#define SPI_SCK 18
#define SPI_MISO 19
#define SPI_MOSI 23
#define DW_CS 4

// connection pins
const uint8_t PIN_RST = 27; // reset pin
const uint8_t PIN_IRQ = 34; // irq pin
const uint8_t PIN_SS = 4;   // spi select pin

// TAG antenna delay defaults to 16384

// leftmost two bytes below will become the "short address"
char tag_addr[] = "7D:00:22:EA:82:60:3B:9C";
float current_tag_position[3] = {0}; //tag current position (meters with respect to origin anchor)
float current_distance_rmse = 0.0;  //error in distance calculations. Crude measure of coordinate error (needs to be characterized)

// variables for position determination
#define N_ANCHORS 5   //THIS VERSION WORKS ONLY WITH 4 ANCHORS. May be generalized to 5 or more.
#define N_ANCHORS_HEX 0x05
#define ANCHOR_DISTANCE_EXPIRED 10000   //measurements older than this are ignore (milliseconds)

float anchor_matrix[N_ANCHORS][3] = { //list of anchor coordinates
  {0.0, 0.0, 0.0},
  {1.6, 0.6, 0.0},
  {0.0, 0.6, 0.0},
  {0.0, 0.0, -0.76},
  {1.55, 0.0, -0.76}
};

uint32_t last_anchor_update[N_ANCHORS] = {0}; //millis() value last time anchor was seen
float last_anchor_distance[N_ANCHORS] = {0.0}; //most recent distance reports

void setup()
{
  Serial.begin(115200);
  delay(1000);

  //initialize configuration
  SPI.begin(SPI_SCK, SPI_MISO, SPI_MOSI);
  DW1000Ranging.initCommunication(PIN_RST, PIN_SS, PIN_IRQ); //Reset, CS, IRQ pin

  DW1000Ranging.attachNewRange(newRange);
  DW1000Ranging.attachNewDevice(newDevice);
  DW1000Ranging.attachInactiveDevice(inactiveDevice);

  // start as tag, do not assign random short address

  DW1000Ranging.startAsTag(tag_addr, DW1000.MODE_LONGDATA_RANGE_LOWPOWER, false);
}

void loop()
{
  DW1000Ranging.loop();
}

// collect distance data from anchors, presently configured for 4 anchors
// solve for position if all four beacons are current

void newRange()
{
  int i;

  //index of this anchor, expecting values 1 to 5
  int index = DW1000Ranging.getDistantDevice()->getShortAddress() & N_ANCHORS_HEX; //expect devices 1 to 7
  Serial.println(index);
  if (index > 0) {
    last_anchor_update[index - 1] = millis();  //(-1) => array index
    float range = DW1000Ranging.getDistantDevice()->getRange();
    last_anchor_distance[index-1] = range;
    #ifdef DEBUG_ANCHOR_ID
      Serial.print(index); //anchor ID, raw range
      Serial.print(" ");
      Serial.println(range);
    #endif
    if (range < 0.0 || range > 30.0)     last_anchor_update[index - 1] = 0;  //sanity check, ignore this measurement
  }
  else {
      Serial.println("index out of range" + index);
  }


  //check for four measurements within the last interval
  int detected = 0;  //count anchors recently seen

  for (i = 0; i < N_ANCHORS; i++) {

    if (millis() - last_anchor_update[i] > ANCHOR_DISTANCE_EXPIRED) last_anchor_update[i] = 0; //not from this one
    if (last_anchor_update[i] > 0) detected++;
  }
  if ( (detected == N_ANCHORS)) { //four recent measurements

#ifdef DEBUG_DISTANCES
    // print distance and age of measurement
    uint32_t current_time = millis();
    for (i = 0; i < N_ANCHORS; i++) {
      Serial.print(last_anchor_distance[i]);
      Serial.print("\t");
      Serial.println(current_time - last_anchor_update[i]); //age in millis
    }
#endif

    //trilat3D_5A();
    test();
    Serial.print("P= ");  //result
    Serial.print(current_tag_position[0]);
    Serial.write(',');
    Serial.print(current_tag_position[1]);
    Serial.write(',');
    Serial.print(current_tag_position[2]);
    Serial.write(',');
    Serial.println(current_distance_rmse);
  }
}  //end newRange

void newDevice(DW1000Device *device)
{
  Serial.print("Device added: ");
  Serial.println(device->getShortAddress(), HEX);
}

void inactiveDevice(DW1000Device *device)
{
  Serial.print("delete inactive device: ");
  Serial.println(device->getShortAddress(), HEX);
}

int test(void){
  for (int i = 0; i < 3; i++) current_tag_position[i] = 1;
}

int trilat3D_5A(void) {

  // for method see technical paper at
  // https://www.th-luebeck.de/fileadmin/media_cosa/Dateien/Veroeffentlichungen/Sammlung/TR-2-2015-least-sqaures-with-ToA.pdf
  // S. J. Remington 1/2022
  //
  // A nice feature of this method is that the normal matrix depends only on the anchor arrangement
  // and needs to be inverted only once. Hence, the position calculation should be robust.
  //
  static bool first = true;  //first time through, some preliminary work
  float b[3], d[N_ANCHORS]; //distances from anchors

  static float Ainv[3][3], k[N_ANCHORS]; //these are calculated only once

  int i;
  // copy distances to local storage
  for (i = 0; i < N_ANCHORS; i++) d[i] = last_anchor_distance[i];

#ifdef DEBUG_TRILAT
  char line[60];
  snprintf(line, sizeof line, "d: %6.2f %6.2f %6.2f d= %6.2f", d[0], d[1], d[2], d[3]);
  Serial.println(line);
#endif

  if (first) {  //intermediate fixed vectors
    first = false;

    float x[N_ANCHORS], y[N_ANCHORS], z[N_ANCHORS]; //intermediate vectors
    float A[3][3];  //the A matrix for system of equations to solve

    for (i = 0; i < N_ANCHORS; i++) {
      x[i] = anchor_matrix[i][0];
      y[i] = anchor_matrix[i][1];
      z[i] = anchor_matrix[i][2];
      k[i] = x[i] * x[i] + y[i] * y[i] + z[i] * z[i];
    }

    // set up the A matrix
    for (i = 1; i < N_ANCHORS; i++) {
      A[i - 1][0] = x[i] - x[0];
      A[i - 1][1] = y[i] - y[0];
      A[i - 1][2] = z[i] - z[0];
#ifdef DEBUG_TRILAT
      snprintf(line, sizeof line, "A %6.2f %6.2f %6.2f", A[i - 1][0], A[i - 1][1], A[i - 1][2]);
      Serial.println(line);
#endif
    }

    float det;
    DETERMINANT_3X3 (det, A);

#ifdef DEBUG_TRILAT
    //    check solution stability (small or zero)
    Serial.print("Determinant of A matrix");
    Serial.println(det);
#endif
    if (fabs(det) < 1.0e-4) {  //TODO : define as parameter
      Serial.println("***Singular matrix, check anchor coordinates***");
      while (1) delay(1); //hang
    }

    det = 1.0 / det;
    SCALE_ADJOINT_3X3 (Ainv, det, A);  //Ainv is static

  } //end if (first)

  // set up least squares equation
  for (i = 1; i < 4; i++) {
    b[i - 1] = d[0] * d[0] - d[i] * d[i] + k[i] - k[0];
  }

  // solve:  2 A x posn = b

  float posn2[3];
  MAT_DOT_VEC_3X3(posn2, Ainv, b);
  // copy to global current_tag_position[]
  for (i = 0; i < 3; i++) current_tag_position[i] = posn2[i] * 0.5; //remove factor of 2

  //rms error in measured versus calculated distances
  float x[3] = {0}, rmse = 0.0, dc = 0.0;
  for (i = 0; i < N_ANCHORS; i++) {
    x[0] = anchor_matrix[i][0] - current_tag_position[0];
    x[1] = anchor_matrix[i][1] - current_tag_position[1];
    x[2] = anchor_matrix[i][2] - current_tag_position[2];
    dc = sqrt(x[0] * x[0] + x[1] * x[1] + x[2] * x[2]);
    rmse += (d[i] - dc) * (d[i] - dc);
  }
  current_distance_rmse = sqrt(rmse / ((float)N_ANCHORS)); //copy to global

  return 1;
}  //end trilat3D_5A
```

**Comment by dmasloub** [comment]
Thanks for you quick answer. This is my modified code. But the problem doesn't lie here, since the raw ranging values between Anchor and Tag already don't come in correctly. As soon as I start a fifth ESP32 as Anchor the values only come in very sporadically, and one anchors always sends wrong ranges with an error of +/- 200m. This is why I feel like the problem lies somewhere in the DW1000 library.

**Comment by dmasloub** [comment]
![Screenshot from 2022-09-15 12-52-15](https://user-images.githubusercontent.com/33729820/190386026-8910c9b3-6db2-4e3a-becc-a1fe1824a1ae.png)

Here I just printed the shortadresses and ranges of each anchor, if you look at the timestamp you can see my problem before the fifth anchor is added the ranges come in every half second or so, afterwards only every 15s or so. And they were all lying on my table next to each other, but the range of '85' is at about 150-200m 

I already checked  the "#define MAX_ANCHORS 7" in the library and it is still at 7, so should theoretically work with 5. 

Any help would be greatly appreciated!!
