### ISSUE TITLE
tag freezes when multiple anchors are active at the same time. When I experiment with multiple anchors, the tag freezes when more than 4 anchors are active at the same time

### ISSUE THREAD

**Issue by hongthiet1994** [jremington/UWB-Indoor-Localization_Arduino#7]
tag freezes when multiple anchors are active at the same time.
When I experiment with multiple anchors, the tag freezes when more than 4 anchors are active at the same time

![image](https://user-images.githubusercontent.com/29925688/196074910-c0ef122f-2368-4e27-90c7-c89a36d3f4a4.png)

**Comment by dmasloub** [comment]
I have the same issue, the DW1000 library is not setup for more than 4 Anchors at the moment. 

In the DW1000Ranging.h on line 48-49 you should be able to choose the number of devices, but there seems to be a bug with more than 4
//Max devices we put in the networkDevices array ! Each DW1000Device is 74 Bytes in SRAM memory for now.
#define MAX_DEVICES 4

I am trying to test and debug right now, but haven't found a solution yet.

**Comment by jremington** [comment]
The localization code accepts only four anchors at the moment. I'm working on generalizing it to four or more, but that is not ready to post.
